3 panels in featured content
dockstore/extra-content pull request #44
Opened 2022-08-03 16:19 UTC by bethsheets

Four looked off in dev display, so I removed the older intro video to have 3 panels only in featured content.

2022-08-03 16:20 UTC, coverbeck approved these changes

2022-08-03 16:21 UTC, coverbeck requested changes

2022-08-03 16:21 UTC, coverbeck commented on feat-content.html
> -    </div>
You want to keep this div

2022-08-03 16:28 UTC, bethsheets commented on feat-content.html
> -    </div>
thanks!

2022-08-03 16:37 UTC, coverbeck approved these changes

2022-08-04 02:28 UTC, svonworl commented
The "content-container" div at line 9 in `feat-content.html` might be spurious, it looks wrong and I can't find a matching `</div>`: https://github.com/dockstore/extra-content/blob/fcf0c67df82251bec4af6c37ecabcd94a22d4bc1/feat-content.html#L9

2022-08-04 02:29 UTC, svonworl reviewed
See other comment.

2022-08-04 16:01 UTC, svonworl approved these changes

2022-08-04 16:02 UTC, merged